### .swiftlint.yml
disabled_rules:
  - unused_closure_parameter
  - trailing_comma
  - line_length
  - trailing_newline
  - todo
  - file_length
  - force_try
  - force_cast
  - function_body_length
  - function_parameter_count
  - large_tuple
  - type_body_length
  - type_name             # allow any length
  - cyclomatic_complexity # allow complex if/switch/for
  - identifier_name       # allow `_`-prefixed variable name
  - nesting               # allow multiple type nesting
  - weak_delegate         # delegate may be a separated class that needs to be retained by core class.
  - colon
  - multiple_closures_with_trailing_closure
  - private_over_fileprivate
  - fallthrough
  - unused_setter_value
  - reduce_boolean
  - unused_capture_list
  - deployment_target
  - legacy_hashing
  - inert_defer
  - closure_parameter_position
  - comment_spacing
  - inclusive_language
  - computed_accessors_order
opt_in_rules:
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discarded_notification_center_observer
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_arrow_whitespace
  - required_enum_case
  - single_test_class
  - sorted_first_last
  # - sorted_imports #swift-formatと競合していたら消す
  - static_operator
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - yoda_condition
